### PR TITLE
certificate can be downloaded as pdf

### PR DESCRIPTION
**Pull request by Krishna100604**

### CODE REVIEW

**Comment by Krishna100604** [comment]
merge this pull request @Durgesh4993

**Comment by Durgesh4993** [comment]
@Krishna100604 Resolve Conflicting files

**Comment by Durgesh4993** [comment]
@Krishna100604 ?

**Comment by Krishna100604** [comment]
> @Krishna100604 ?

i think you merged some wrong pull request and that is conflicting with mine so that's why this issue is occuring you can pull my request and the code you pulled yesterday has made css bad you can cross check it

**Pull request closed without merging**
